# Generated by Django 5.2.7 on 2025-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=9)),
                ('activo', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_dato', models.CharField(max_length=7)),
                ('categoria', models.CharField(max_length=50)),
                ('modificable_usuario', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('especificaciones_tecnicas', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=17)),
                ('fecha_adquision', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('activo', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantenimiento', models.CharField(max_length=11)),
                ('fecha_mantenimiento', models.DateField()),
                ('descripcion', models.TextField()),
                ('realizado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id_organismo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cientifico', models.CharField(max_length=255)),
                ('cepa', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_identificacion', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo', models.CharField(max_length=19)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('caracteristicas_morfologicas', models.TextField(blank=True, null=True)),
                ('condiciones_cultivo', models.TextField(blank=True, null=True)),
                ('temperatura_optima', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph_optimo', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organismo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id_protocolo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('procedimiento', models.TextField()),
                ('materiales', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=11)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'protocolo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtocoloEquipo',
            fields=[
                ('id_protocolo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_asociacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'protocolo_equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtocoloOrganismo',
            fields=[
                ('id_protocolo_organismo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_relacion', models.CharField(max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_asociacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'protocolo_organismo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=13)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
