# Generated by Django 5.2.7 on 2025-11-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloArchivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='protocolos/%Y/%m/%d/')),
                ('nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.protocolo')),
            ],
            options={
                'db_table': 'protocolo_archivo',
                'managed': True,
            },
        ),
    ]
